import baseConfig from 'base.config';

export default {
  apiBasePath: 'http://tve-web1-dev.corbina.net/api_v3/service', // API base path is updated once after successful DMS request
  apiVersion: '4.4.1.25797',
  applicationName: 'com.Kaltura.beeline.ctv',
  clientVersion: '0.0.1',
  platform: 'ctv',
  partnerId: '478',
  tag: '', // TODO Group ID tag (to be provided)
  deviceFamilyMap: {
    1: 'mobile',
    2: 'tv',
    3: 'tv',
    4: 'tablet',
    5: 'desktop',
    6: 'game',
  },
  deviceBrandsMap: {
    1: 'iPhone',
    2: 'Samsung Galaxy S',
    3: 'iPad',
    4: 'Samsung Galaxy Tab',
    5: 'PeerTV',
    6: 'Vestel',
    7: 'Vantage',
    8: 'Boxee',
    9: 'Samsung',
    10: 'Toshiba',
    11: 'HTC',
    12: 'Blackberry',
    13: 'Netgem',
    14: 'Roku',
    15: 'YouView',
    16: 'LG',
    17: 'Panasonic',
    18: 'Phillips',
    19: 'Sony',
    20: 'Samsung',
    21: 'Motorola Xoom',
    22: 'Desktop',
    23: 'PC/MAC Application',
    24: 'XBox',
    25: 'Playstation 3',
    26: 'Wii',
    27: 'Google TV',
    28: 'T20',
    29: 'Zappaware',
    30: 'Oregan',
    31: 'Android',
    32: 'Android',
    33: 'ABox42',
    34: 'Kaon',
    36: 'Sagemcom',
    39: 'Velazquez',
    102: 'AppleTV',
    103: 'Thyssen',
    104: 'Amazon Fire',
    105: 'Android TV',
  },
  ...baseConfig,
};
